/**
 * Pre-computed scheme code lookup for mfapi.in.
 * Scheme codes were matched offline — eliminates 7MB runtime download.
 */

export interface SchemeEntry {
  schemeCode: number
  schemeName: string
  fundName:   string
}

export const SCHEME_ENTRIES: SchemeEntry[] = [
  { schemeCode: 100822, schemeName: "UTI Nifty 50 Index Fund - Regular Plan - Growth Option", fundName: "UTI Nifty 50 Index Fund-Reg(G)" },
  { schemeCode: 101525, schemeName: "HDFC Nifty 50 Index Fund - Growth Plan", fundName: "HDFC Nifty 50 Index Fund(G)(Post Addendum)" },
  { schemeCode: 111954, schemeName: "SBI Gold ETF", fundName: "SBI Gold-Reg(G)" },
  { schemeCode: 101349, schemeName: "ICICI Prudential Nifty 50 Index Fund - Cumulative Option", fundName: "ICICI Pru Nifty 50 Index Fund-Reg(G)" },
  { schemeCode: 102272, schemeName: "SBI NIFTY INDEX FUND - REGULAR PLAN - GROWTH", fundName: "SBI Nifty Index Fund-Reg(G)" },
  { schemeCode: 115934, schemeName: "HDFC Gold ETF FoF(G)", fundName: "HDFC Gold ETF FoF(G)" },
  { schemeCode: 101281, schemeName: "HDFC BSE Sensex Index Fund - Growth Plan", fundName: "HDFC BSE Sensex Index Fund(G)(Post Addendum)" },
  { schemeCode: 148704, schemeName: "UTI Nifty200 Momentum 30 Index Fund-Reg(G)", fundName: "UTI Nifty200 Momentum 30 Index Fund-Reg(G)" },
  { schemeCode: 112957, schemeName: "ICICI Prudential Nifty Next 50 Index Fund - Growth", fundName: "ICICI Pru Nifty Next 50 Index Fund(G)" },
  { schemeCode: 114616, schemeName: "Nippon India Gold Savings Fund-Growth plan- Growth Option", fundName: "Nippon India Gold Savings Fund(G)" },
  { schemeCode: 114758, schemeName: "Kotak Gold Fund Growth", fundName: "Kotak Gold Fund(G)" },
  { schemeCode: 115833, schemeName: "ICICI Prudential Gold ETF FOF - Growth", fundName: "ICICI Pru Gold ETF FOF(G)" },
  { schemeCode: 143340, schemeName: "UTI Nifty Next 50 Index Fund - Regular Plan - Growth Option", fundName: "UTI Nifty Next 50 Index Fund-Reg(G)" },
  { schemeCode: 150736, schemeName: "HDFC Silver ETF FoF-Reg(G)", fundName: "HDFC Silver ETF FoF-Reg(G)" },
  { schemeCode: 152846, schemeName: "Motilal Oswal Nifty India Defence ETF", fundName: "Motilal Oswal Nifty India Defence Index Fund-Reg(G)" },
  { schemeCode: 151688, schemeName: "Navi Nifty 50 Index Fund-Reg(G)", fundName: "Navi Nifty 50 Index Fund-Reg(G)" },
  { schemeCode: 113296, schemeName: "Nippon India Index Fund-Nifty 50 Plan(G)", fundName: "Nippon India Index Fund-Nifty 50 Plan(G)" },
  { schemeCode: 147621, schemeName: "Motilal Oswal Nifty Midcap 150 Index Fund - Regular Plan", fundName: "Motilal Oswal Nifty Midcap 150 Index Fund-Reg(G)" },
  { schemeCode: 115897, schemeName: "Axis Gold Fund - Regular Plan - Growth Option", fundName: "Axis Gold Fund-Reg(G)" },
  { schemeCode: 147626, schemeName: "Motilal Oswal Nifty 500 Index Fund - Regular Plan", fundName: "Motilal Oswal Nifty 500 Index Fund-Reg(G)" },
  { schemeCode: 148518, schemeName: "Nippon India Nifty Smallcap 250 Index Fund - Regular Plan - Growth Option", fundName: "Nippon India Nifty Smallcap 250 Index Fund-Reg(G)" },
  { schemeCode: 150641, schemeName: "Motilal Oswal Gold and Silver Passive Fund of Funds(Regular Plan)", fundName: "Motilal Oswal Gold and Silver Passive FoF-Reg(G)" },
  { schemeCode: 141876, schemeName: "DSP Nifty 50 Equal Weight Index Fund - Regular Plan - IDCW", fundName: "DSP Nifty 50 Equal Weight Index Fund-Reg(G)" },
  { schemeCode: 151815, schemeName: "Motilal Oswal Nifty Microcap 250 Index Fund- Regular- Growth Option", fundName: "Motilal Oswal Nifty Microcap 250 Index Fund-Reg(G)" },
  { schemeCode: 149287, schemeName: "HDFC NIFTY Next 50 Index Fund - Growth Option", fundName: "HDFC NIFTY Next 50 Index Fund-Reg(G)" },
  { schemeCode: 112878, schemeName: "BANDHAN Nifty 50 Index Fund - Regular Plan - IDCW", fundName: "Bandhan Nifty 50 Index Fund-Reg(G)" },
  { schemeCode: 148723, schemeName: "Nippon India Nifty Midcap 150 Index Fund - Regular Plan - Growth Option", fundName: "Nippon India Nifty Midcap 150 Index Fund-Reg(G)" },
  { schemeCode: 150538, schemeName: "ICICI Prudential PSU Equity Fund - Growth", fundName: "ICICI Pru PSU Equity Fund-Reg(G)" },
  { schemeCode: 147665, schemeName: "Axis Nifty 100 Index Fund - Regular Plan - Growth Option", fundName: "Axis Nifty 100 Index Fund-Reg(G)" },
  { schemeCode: 143340, schemeName: "UTI Nifty Next 50 Index Fund - Regular Plan - Growth Option", fundName: "SBI Nifty Next 50 Index Fund-Reg(G)" },
  { schemeCode: 149802, schemeName: "UTI BSE Sensex Index Fund - Regular Plan  -Growth Option", fundName: "ICICI Pru BSE Sensex Index Fund(G)" },
  { schemeCode: 150633, schemeName: "BANDHAN NIFTY100 LOW VOLATILITY 30 INDEX FUND - GROWTH - REGULAR PLAN", fundName: "Bandhan Nifty100 Low Volatility 30 Index Fund-Reg(G)" },
  { schemeCode: 116796, schemeName: "Aditya Birla Sun Life Gold Fund-Growth", fundName: "Aditya Birla SL Gold Fund-Reg(G)" },
  { schemeCode: 150519, schemeName: "Motilal Oswal BSE Enhanced Value Index Fund-Regular plan", fundName: "Motilal Oswal BSE Enhanced Value Index Fund-Reg(G)" },
  { schemeCode: 149106, schemeName: "HDFC NIFTY50 Equal weight Index Fund - Growth Option", fundName: "HDFC NIFTY50 Equal Weight Index Fund-Reg(G)" },
  { schemeCode: 101659, schemeName: "Tata Nifty 50 Index Fund -Regular Plan", fundName: "Tata NIFTY 50 Index Fund-Reg(G)" },
  { schemeCode: 150901, schemeName: "Edelweiss Nifty Midcap150 Momentum 50 Index Fund - Regular Plan - IDCW", fundName: "Edelweiss Nifty Midcap150 Momentum 50 Index Fund-Reg(G)" },
  { schemeCode: 150676, schemeName: "SBI Nifty Smallcap 250 Index Fund - Regular Plan - Growth", fundName: "SBI Nifty Smallcap 250 Index Fund-Reg(G)" },
  { schemeCode: 150490, schemeName: "Nippon India Nifty Alpha Low Volatility 30 Index Fund - Regular Plan - Growth Option", fundName: "Nippon India Nifty Alpha Low Volatility 30 Index Fund(G)" },
  { schemeCode: 150715, schemeName: "UTI Gold ETF FoF-Reg(G)", fundName: "UTI Gold ETF FoF-Reg(G)" },
  { schemeCode: 152813, schemeName: "DSP Nifty Top 10 Equal Weight Index Fund - Regular - Growth", fundName: "DSP Nifty Top 10 Equal Weight Index Fund-Reg(G)" },
  { schemeCode: 101314, schemeName: "Aditya Birla Sun Life Nifty 50 Index Fund - Growth - Regular Plan", fundName: "Aditya Birla SL Nifty 50 Index Fund-Reg(G)" },
  { schemeCode: 150617, schemeName: "Axis Silver FoF-Reg(G)", fundName: "Axis Silver FoF-Reg(G)" },
  { schemeCode: 146383, schemeName: "DSP Nifty Next 50 Index Fund - Regular Plan - IDCW", fundName: "DSP NIFTY Next 50 Index Fund-Reg(G)" },
  { schemeCode: 143340, schemeName: "UTI Nifty Next 50 Index Fund - Regular Plan - Growth Option", fundName: "Navi Nifty Next 50 Index Fund-Reg(G)" },
  { schemeCode: 152883, schemeName: "Nippon India Nifty 500 Momentum 50 Index Fund - Regular Plan - Growth Option", fundName: "Nippon India Nifty 500 Momentum 50 Index Fund-Reg(G)" },
  { schemeCode: 153922, schemeName: "Kotak Gold Silver Passive FOF - Regular Plan - Growth", fundName: "Kotak Gold Silver Passive FOF-Reg(G)" },
  { schemeCode: 150741, schemeName: "Tata Nifty Midcap 150 Momentum 50 Index Fund - Growth - Regular Plan", fundName: "Tata Nifty Midcap 150 Momentum 50 Index Fund-Reg(G)" },
  { schemeCode: 151761, schemeName: "UTI Nifty50 Equal Weight Index Fund - Regular Plan - Growth Option", fundName: "SBI Nifty50 Equal Weight Index Fund-Reg(G)" },
  { schemeCode: 148974, schemeName: "Kotak Nifty 50 Index Fund - Regular Plan-Growth", fundName: "Kotak Nifty 50 Index Fund-Reg(G)" },
  { schemeCode: 148719, schemeName: "Nippon India Nifty 50 Value 20 Index Fund - Regular Plan - Growth Option", fundName: "Nippon India Nifty 50 Value 20 Index Fund-Reg(G)" },
  { schemeCode: 147624, schemeName: "Motilal Oswal Nifty Smallcap 250 Index - Regular Plan", fundName: "Motilal Oswal Nifty Smallcap 250 Index Fund-Reg(G)" },
  { schemeCode: 151602, schemeName: "Kotak Silver ETF FoF-Reg(G)", fundName: "Kotak Silver ETF FoF-Reg(G)" },
  { schemeCode: 146378, schemeName: "DSP Nifty 50 Index Fund - Regular Plan - IDCW", fundName: "DSP NIFTY 50 Index Fund-Reg(G)" },
  { schemeCode: 149799, schemeName: "Motilal Oswal Nifty 200 Momentum 30 Index Fund-Regular Plan", fundName: "Motilal Oswal Nifty 200 Momentum 30 Index Fund-Reg(G)" },
  { schemeCode: 153088, schemeName: "UTI Nifty Midcap 150 Index Fund - Regular Plan - Growth Option", fundName: "SBI Nifty Midcap 150 Index Fund-Reg(G)" },
  { schemeCode: 149390, schemeName: "ICICI Prudential Nifty Midcap 150 Index Fund - Growth", fundName: "ICICI Pru Nifty Midcap 150 Index Fund-Reg(G)" },
  { schemeCode: 113269, schemeName: "Nippon India Index Fund-BSE Sensex Plan(G)", fundName: "Nippon India Index Fund-BSE Sensex Plan(G)" },
  { schemeCode: 148743, schemeName: "Kotak Nifty Next 50 Index Fund - Regular Plan - Growth Option", fundName: "Kotak Nifty Next 50 Index Fund-Reg(G)" },
  { schemeCode: 152800, schemeName: "Aditya Birla Sun Life Nifty India Defence Index Fund-Regular-Growth", fundName: "Aditya Birla SL Nifty India Defence Index Fund-Reg(G)" },
  { schemeCode: 147795, schemeName: "Motilal Oswal Nifty 50 Index Fund - Regular plan - Growth", fundName: "Motilal Oswal Nifty 50 Index Fund-Reg(G)" },
  { schemeCode: 149371, schemeName: "Axis Nifty 50 Index Fund - Regular Plan - Growth Option", fundName: "Axis Nifty 50 Index Fund-Reg(G)" },
  { schemeCode: 151973, schemeName: "LIC MF Gold ETF FoF(G)", fundName: "LIC MF Gold ETF FoF(G)" },
  { schemeCode: 151770, schemeName: "SBI BSE Sensex Index Fund - Direct Plan - IDCW", fundName: "SBI Nifty 500 Index Fund-Reg(G)" },
  { schemeCode: 100484, schemeName: "Franklin India Index Fund- NSE Nifty 50 Index Fund - Growth", fundName: "Franklin India NSE Nifty 50 Index Fund(G)" },
  { schemeCode: 149799, schemeName: "Motilal Oswal Nifty 200 Momentum 30 Index Fund-Regular Plan", fundName: "Motilal Oswal Nifty 500 Momentum 50 Index Fund-Reg(G)" },
  { schemeCode: 149859, schemeName: "ICICI Prudential Nifty Bank Index Fund - Growth", fundName: "ICICI Pru Nifty Bank Index Fund-Reg(G)" },
  { schemeCode: 147619, schemeName: "Motilal Oswal Nifty Bank Index - Regular Plan", fundName: "Motilal Oswal Nifty Bank Index Fund-Reg(G)" },
  { schemeCode: 149805, schemeName: "Navi Nifty Bank Index Fund- Regular Plan- Growth", fundName: "Navi Nifty Bank Index Fund-Reg(G)" },
  { schemeCode: 152429, schemeName: "HDFC NIFTY200 Momentum 30 Index Fund - Regular Plan", fundName: "HDFC NIFTY200 Momentum 30 Index Fund-Reg(G)" },
  { schemeCode: 151738, schemeName: "UTI Nifty 500 Value 50 Index Fund - Regular Plan - Growth Option", fundName: "UTI Nifty 500 Value 50 Index Fund-Reg(G)" },
  { schemeCode: 152858, schemeName: "UTI Nifty200 Quality 30 Index Fund-Reg(G)", fundName: "UTI Nifty200 Quality 30 Index Fund-Reg(G)" },
  { schemeCode: 149938, schemeName: "Axis Nifty Midcap 50 Index Fund - Regular Plan - Growth Option", fundName: "Axis Nifty Midcap 50 Index Fund-Reg(G)" },
  { schemeCode: 149281, schemeName: "ICICI Prudential Nifty Smallcap 250 Index Fund - Growth", fundName: "ICICI Pru Nifty Smallcap 250 Index Fund(G)" },
  { schemeCode: 154077, schemeName: "Axis Gold and Silver Passive FOF - Regular Plan - Growth", fundName: "Axis Gold and Silver Passive FoF-Reg(G)" },
  { schemeCode: 150454, schemeName: "ICICI Prudential Nifty 200 Momentum 30 Index Fund - Growth", fundName: "ICICI Pru Nifty 200 Momentum 30 Index Fund-Reg(G)" },
  { schemeCode: 151726, schemeName: "HDFC NIFTY Smallcap 250 Index Fund - Growth Option", fundName: "HDFC NIFTY Smallcap 250 Index Fund-Reg(G)" },
  { schemeCode: 149896, schemeName: "Axis Nifty Smallcap 50 Index Fund - Regular Plan - Growth Option", fundName: "Axis Nifty Smallcap 50 Index Fund-Reg(G)" },
  { schemeCode: 152182, schemeName: "DSP Gold ETF FoF-Reg(G)", fundName: "DSP Gold ETF FoF-Reg(G)" },
  { schemeCode: 149880, schemeName: "UTI BSE Low Volatility Index Fund - Regular Plan - Growth Option", fundName: "UTI BSE Low Volatility Index Fund-Reg(G)" },
  { schemeCode: 152985, schemeName: "Edelweiss Nifty500 Multicap Momentum Quality 50 Index Fund - Direct - Growth", fundName: "Edelweiss Nifty500 Multicap Momentum Quality 50 Index Fund-Reg(G)" },
  { schemeCode: 152180, schemeName: "Bandhan Nifty Alpha 50 Index Fund - Regular Plan - IDCW", fundName: "Bandhan Nifty Alpha 50 Index Fund-Reg(G)" },
  { schemeCode: 150466, schemeName: "ICICI Prudential Nifty IT Index Fund - Growth", fundName: "ICICI Pru Nifty IT Index Fund-Reg(G)" },
  { schemeCode: 141064, schemeName: "Quantum Gold Savings Fund - Regular Plan Growth Option", fundName: "Quantum Gold Saving Fund-Reg(G)" },
  { schemeCode: 151725, schemeName: "HDFC NIFTY Midcap 150 Index Fund - Growth Option", fundName: "HDFC NIFTY Midcap 150 Index Fund-Reg(G)" },
  { schemeCode: 151783, schemeName: "Kotak Nifty 200 Momentum 30 Index Fund - Regular Plan - Growth Option", fundName: "Kotak Nifty 200 Momentum 30 Index Fund-Reg(G)" },
  { schemeCode: 152954, schemeName: "Tata Nifty Capital Markets Index Fund - Regular Plan Growth Option", fundName: "Tata Nifty Capital Markets Index Fund-Reg(G)" },
  { schemeCode: 116077, schemeName: "Invesco India Gold ETF FoF-Reg(G)", fundName: "Invesco India Gold ETF FoF-Reg(G)" },
  { schemeCode: 148964, schemeName: "Aditya Birla Sun Life Nifty 50 Equal Weight Index Fund-Regular IDCW", fundName: "Aditya Birla SL Nifty 50 Equal Weight Index Fund-Reg(G)" },
  { schemeCode: 150430, schemeName: "DSP Nifty Midcap 150 Quality 50 Index Fund - Regular - IDCW", fundName: "DSP Nifty Midcap 150 Quality 50 Index Fund-Reg(G)" },
  { schemeCode: 149371, schemeName: "Axis Nifty 50 Index Fund - Regular Plan - Growth Option", fundName: "Axis Nifty Next 50 Index Fund-Reg(G)" },
  { schemeCode: 152779, schemeName: "HDFC NIFTY500 Multicap 50:25:25 index Fund - Regular Plan", fundName: "HDFC Nifty500 Multicap 50:25:25 Index Fund-Reg(G)" },
  { schemeCode: 147626, schemeName: "Motilal Oswal Nifty 500 Index Fund - Regular Plan", fundName: "Motilal Oswal Nifty Next 50 Index Fund-Reg(G)" },
  { schemeCode: 148805, schemeName: "Aditya Birla Sun Life Nifty Midcap 150 Index Fund-Regular Growth", fundName: "Aditya Birla SL Nifty Midcap 150 Index Fund-Reg(G)" },
  { schemeCode: 152890, schemeName: "HDFC NIFTY LargeMidcap 250 Index Fund - Growth Option", fundName: "HDFC Nifty LargeMidcap 250 Index Fund-Reg(G)" },
  { schemeCode: 149871, schemeName: "HDFC Nifty 100 Equal Weight Index Fund - Growth Option", fundName: "HDFC NIFTY 100 Equal Weight Index Fund-Reg(G)" },
  { schemeCode: 149869, schemeName: "HDFC NIFTY 100 Index Fund - Growth Option", fundName: "HDFC NIFTY 100 Index Fund-Reg(G)" },
  { schemeCode: 101746, schemeName: "Tata S&P BSE Sensex Index Fund -Regular Plan", fundName: "Tata BSE Sensex Index Fund-Reg(G)" },
  { schemeCode: 152840, schemeName: "Nippon India Nifty 500 Equal Weight Index Fund - Regular Plan - Growth Option", fundName: "Nippon India Nifty 500 Equal Weight Index Fund-Reg(G)" },
  { schemeCode: 151159, schemeName: "HSBC NIFTY 50 INDEX FUND - Regular IDCW", fundName: "HSBC Nifty 50 Index Fund-Reg(G)" },
  { schemeCode: 153088, schemeName: "UTI Nifty Midcap 150 Index Fund - Regular Plan - Growth Option", fundName: "Navi Nifty Midcap 150 Index Fund-Reg(G)" },
  { schemeCode: 101200, schemeName: "LIC MF Nifty 50 Index Fund-Regular Plan-IDCW", fundName: "LIC MF Nifty 50 Index Fund(G)" },
  { schemeCode: 153137, schemeName: "Motilal Oswal Nifty Capital Market Index Fund - Regular Plan - Growth", fundName: "Motilal Oswal Nifty Capital Market Index Fund-Reg(G)" },
  { schemeCode: 152126, schemeName: "Groww Nifty Total Market Index Fund - Regular Plan - IDCW", fundName: "Groww Nifty Total Market Index Fund-Reg(G)" },
  { schemeCode: 149341, schemeName: "Edelweiss NIFTY Large Mid Cap 250 Index Fund-Reg(G)", fundName: "Edelweiss NIFTY Large Mid Cap 250 Index Fund-Reg(G)" },
  { schemeCode: 150741, schemeName: "Tata Nifty Midcap 150 Momentum 50 Index Fund - Growth - Regular Plan", fundName: "Kotak NIFTY Midcap 150 Momentum 50 Index Fund-Reg(G)" },
  { schemeCode: 152730, schemeName: "Axis Nifty 500 Index Fund - Regular Plan - Growth Option", fundName: "Axis Nifty 500 Index Fund-Reg(G)" },
  { schemeCode: 151766, schemeName: "SBI BSE Sensex Index Fund - Regular Plan - IDCW", fundName: "SBI BSE Sensex Index Fund-Reg(G)" },
  { schemeCode: 152858, schemeName: "UTI Nifty 200 Quality 30 Index Fund - Regular Plan - Growth Option", fundName: "SBI Nifty200 Quality 30 Index Fund-Reg(G)" },
  { schemeCode: 153434, schemeName: "SBI BSE PSU BANK INDEX FUND- Regular Plan- Growth", fundName: "SBI BSE PSU Bank Index Fund-Reg(G)" },
  { schemeCode: 152242, schemeName: "DSP Nifty Smallcap250 Quality 50 Index Fund - Regular - IDCW", fundName: "DSP Nifty Smallcap250 Quality 50 Index Fund-Reg(G)" },
  { schemeCode: 153012, schemeName: "SBI Nifty India Consumption Index Fund- Regular Plan- Growth", fundName: "SBI Nifty India Consumption Index Fund-Reg(G)" },
  { schemeCode: 151729, schemeName: "HDFC BSE 500 Index Fund - Regular Plan - Growth Option", fundName: "HDFC BSE 500 Index Fund-Reg(G)" },
  { schemeCode: 149252, schemeName: "Edelweiss Nifty 50 Index Fund Regular Plan Growth", fundName: "Edelweiss Nifty 50 Index Fund-Reg(G)" },
  { schemeCode: 152742, schemeName: "Tata Nifty India Tourism Index Fund - Direct - Growth", fundName: "Tata Nifty India Tourism Index Fund-Reg(G)" },
  { schemeCode: 152714, schemeName: "HDFC NIFTY100 Low Volatility 30 Index Fund - Regular Plan", fundName: "HDFC NIFTY100 Low Volatility 30 Index Fund-Reg(G)" },
  { schemeCode: 148811, schemeName: "Aditya Birla Sun Life Nifty Smallcap 50 Index Fund-Regular Growth", fundName: "Aditya Birla SL Nifty Smallcap 50 Index Fund-Reg(G)" },
  { schemeCode: 152481, schemeName: "ICICI Prudential Nifty LargeMidcap 250 Index Fund - Growth", fundName: "ICICI Pru Nifty LargeMidcap 250 Index Fund-Reg(G)" },
  { schemeCode: 149836, schemeName: "Aditya Birla Sun Life Nifty Next 50 Index Fund-Regular IDCW", fundName: "Aditya Birla SL Nifty Next 50 Index Fund-Reg(G)" },
  { schemeCode: 150312, schemeName: "UTI Nifty Midcap 150 Quality 50 Index Fund - Regular Plan - Growth Option", fundName: "UTI Nifty Midcap 150 Quality 50 Index Fund-Reg(G)" },
  { schemeCode: 149834, schemeName: "BANDHAN NIFTY 100 INDEX FUND - REGULAR PLAN - IDCW", fundName: "Bandhan Nifty 100 Index Fund-Reg(G)" },
  { schemeCode: 153580, schemeName: "Tata Nifty Midcap 150 Index Fund - Regular Plan - Growth Option", fundName: "Tata Nifty Midcap 150 Index Fund-Reg(G)" },
  { schemeCode: 153134, schemeName: "Tata BSE Select Business Groups Index Fund - Regular Growth", fundName: "Tata BSE Select Business Groups Index Fund-Reg(G)" },
  { schemeCode: 152865, schemeName: "UTI Nifty Private Bank Index Fund - Regular Plan - Growth Option", fundName: "UTI Nifty Private Bank Index Fund-Reg(G)" },
  { schemeCode: 150898, schemeName: "Edelweiss Nifty Next 50 Index Fund - Regular Plan - IDCW", fundName: "Edelweiss Nifty Next 50 Index Fund-Reg(G)" },
  { schemeCode: 150637, schemeName: "ICICI Prudential Nifty50 Equal Weight Index Fund- Growth", fundName: "ICICI Pru Nifty50 Equal Weight Index Fund-Reg(G)" },
  { schemeCode: 149802, schemeName: "UTI BSE Sensex Index Fund - Regular Plan  -Growth Option", fundName: "UTI BSE Sensex Index Fund-Reg(G)" },
  { schemeCode: 152934, schemeName: "ICICI Prudential Nifty200 Value 30 Index Fund - Growth", fundName: "ICICI Pru Nifty200 Value 30 Index Fund-Reg(G)" },
  { schemeCode: 152834, schemeName: "Tata Nifty200 Alpha 30 Index Fund - Regular -Growth", fundName: "Tata Nifty200 Alpha 30 Index Fund-Reg(G)" },
  { schemeCode: 150893, schemeName: "Edelweiss Nifty Smallcap 250 Index Fund - Regular Plan - IDCW", fundName: "Edelweiss Nifty Smallcap 250 Index Fund-Reg(G)" },
  { schemeCode: 153958, schemeName: "HDFC BSE India Sector Leaders Index Fund - Regular Plan - Growth Option", fundName: "HDFC BSE India Sector Leaders Index Fund-Reg(G)" },
  { schemeCode: 152387, schemeName: "Nippon India Nifty Bank Index Fund - Regular Plan - Growth Option", fundName: "Nippon India Nifty Bank Index Fund-Reg(G)" },
  { schemeCode: 152391, schemeName: "Nippon India Nifty IT Index Fund - Regular Plan - Growth Option", fundName: "Nippon India Nifty IT Index Fund-Reg(G)" },
  { schemeCode: 151648, schemeName: "Kotak Nifty Smallcap 50 Index Fund - Regular Plan - IDCW", fundName: "Kotak Nifty Smallcap 50 Index Fund-Reg(G)" },
  { schemeCode: 148555, schemeName: "Edelweiss MSCI India Domestic & World Healthcare 45 Index Fund Direct Plan - Growth", fundName: "Edelweiss MSCI India Domestic & World Healthcare 45 Index Fund-Reg(G)" },
  { schemeCode: 153338, schemeName: "Union Gold ETF FoF-Reg(G)", fundName: "Union Gold ETF FoF-Reg(G)" },
  { schemeCode: 154180, schemeName: "HDFC Nifty India Consumption Index  Fund - Regular Growth Plan", fundName: "HDFC Nifty India Consumption Index Fund-Reg(G)" },
  { schemeCode: 152567, schemeName: "Tata Nifty MidSmall Healthcare Index Fund - Regular Plan - Growth", fundName: "Tata Nifty MidSmall Healthcare Index Fund-Reg(G)" },
  { schemeCode: 153929, schemeName: "Bandhan Silver ETF", fundName: "Bandhan Silver ETF FOF-Reg(G)" },
  { schemeCode: 153265, schemeName: "HDFC Nifty100 Quality 30 Index Fund - Regular Plan", fundName: "HDFC Nifty100 Quality 30 Index Fund-Reg(G)" },
  { schemeCode: 152632, schemeName: "Axis Nifty Bank Index Fund - Regular Plan - Growth Option", fundName: "Axis Nifty Bank Index Fund-Reg(G)" },
  { schemeCode: 151161, schemeName: "HSBC NIFTY NEXT 50 INDEX FUND - Regular IDCW", fundName: "HSBC Nifty Next 50 Index Fund-Reg(G)" },
  { schemeCode: 152950, schemeName: "Axis Nifty500 Value 50 Index Fund - Regular Plan - Growth Option", fundName: "Axis Nifty500 Value 50 Index Fund-Reg(G)" },
  { schemeCode: 153253, schemeName: "SBI Nifty Bank Index Fund-Regular Plan- Growth", fundName: "SBI Nifty Bank Index Fund-Reg(G)" },
  { schemeCode: 139367, schemeName: "Edelweiss ETF - Nifty 100 Quality 30", fundName: "Edelweiss Nifty 100 Quality 30 Index Fund-Reg(G)" },
  { schemeCode: 153096, schemeName: "HDFC Nifty India Digital Index Fund - Growth Option - Regular", fundName: "HDFC Nifty India Digital Index Fund-Reg(G)" },
  { schemeCode: 140452, schemeName: "Sundaram Smart Nifty 100 Equal Weight Fund Regular Plan - Growth", fundName: "Sundaram Nifty 100 Equal Weight Fund(G)" },
  { schemeCode: 150592, schemeName: "BANDHAN NIFTY200 MOMENTUM 30 INDEX FUND - GROWTH - REGULAR PLAN", fundName: "Bandhan Nifty200 Momentum 30 Index Fund-Reg(G)" },
  { schemeCode: 152664, schemeName: "Kotak NIFTY 100 Low Volatility 30 Index Fund - Regular plan - Growth option", fundName: "Kotak NIFTY 100 Low Volatility 30 Index Fund-Reg(G)" },
  { schemeCode: 153803, schemeName: "DSP Nifty500 Flexicap Quality 30 Index Fund - Regular - IDCW", fundName: "DSP Nifty500 Flexicap Quality 30 Index Fund-Reg(G)" },
  { schemeCode: 154130, schemeName: "Bandhan Gold ETF FOF-Regular-Growth", fundName: "Bandhan Gold ETF FOF-Reg(G)" },
  { schemeCode: 151761, schemeName: "UTI Nifty50 Equal Weight Index Fund - Regular Plan - Growth Option", fundName: "UTI NIFTY50 Equal Weight Index Fund-Reg(G)" },
  { schemeCode: 153245, schemeName: "Axis Nifty500 Momentum 50 Index Fund - Regular Plan - Growth Option", fundName: "Axis Nifty500 Momentum 50 Index Fund-Reg(G)" },
  { schemeCode: 152590, schemeName: "Tata Nifty500 Multicap India Manufacturing 50:30:20 Index Fund -Regular Plan-Growth", fundName: "Tata Nifty500 Multicap India Manufacturing 50:30:20 Index Fund-Reg(G)" },
  { schemeCode: 152212, schemeName: "Edelweiss Silver ETF", fundName: "Edelweiss Silver ETF FoF-Reg(G)" },
  { schemeCode: 151784, schemeName: "Axis Nifty IT Index Fund - Regular Plan - IDCW", fundName: "Axis NIFTY IT Index Fund-Reg(G)" },
  { schemeCode: 152617, schemeName: "Edelweiss Nifty Alpha Low Volatility 30 Index Fund - Regular Plan - Growth", fundName: "Edelweiss Nifty Alpha Low Volatility 30 Index Fund-Reg(G)" },
  { schemeCode: 152433, schemeName: "Groww Nifty Smallcap 250 Index Fund - Regular Plan - Growth", fundName: "Groww Nifty Smallcap 250 Index Fund-Reg(G)" },
  { schemeCode: 153006, schemeName: "Groww Gold ETF FOF - REGULAR - GROWTH", fundName: "Groww Gold ETF FOF-Reg(G)" },
  { schemeCode: 153663, schemeName: "SBI Nifty200 Momentum 30 Index Fund- Regular Plan- Growth", fundName: "SBI Nifty200 Momentum 30 Index Fund-Reg(G)" },
  { schemeCode: 153855, schemeName: "Tata Nifty Next 50 Index Fund - Regular Plan Growth Option", fundName: "Tata Nifty Next 50 Index Fund-Reg(G)" },
  { schemeCode: 149920, schemeName: "Motilal Oswal BSE Low Volatility Index Fund-Regular plan", fundName: "Motilal Oswal BSE Low Volatility Index Fund-Reg(G)" },
  { schemeCode: 152366, schemeName: "ICICI Prudential Nifty50 Value 20 Index Fund - Growth", fundName: "ICICI Pru Nifty50 Value 20 Index Fund-Reg(G)" },
  { schemeCode: 152522, schemeName: "HDFC NIFTY Reality Index Fund - Regular Plan", fundName: "HDFC NIFTY Realty Index Fund-Reg(G)" },
  { schemeCode: 151936, schemeName: "LIC MF Nifty Next 50 Index Fund-Regular Plan-IDCW", fundName: "LIC MF Nifty Next 50 Index Fund(G)" },
  { schemeCode: 151909, schemeName: "Kotak Nifty Financial Services Ex-Bank Index Fund - Regular Plan - Growth option", fundName: "Kotak Nifty Financial Services Ex-Bank Index Fund-Reg(G)" },
  { schemeCode: 153273, schemeName: "UTI Nifty Midsmallcap 400 Momentum Quality 100 Index Fund - Regular Plan - Growth Option", fundName: "UTI Nifty Midsmallcap 400 Momentum Quality 100 Index Fund-Reg(G)" },
  { schemeCode: 152752, schemeName: "Kotak BSE PSU Index Fund - Regular Plan - Growth", fundName: "Kotak BSE PSU Index Fund-Reg(G)" },
  { schemeCode: 101198, schemeName: "LIC MF BSE Sensex Index Fund-Regular Plan-IDCW", fundName: "LIC MF BSE Sensex Index Fund-Reg(G)" },
  { schemeCode: 153404, schemeName: "HDFC Nifty Top 20 Equal Weight Index Fund - Regular Growth", fundName: "HDFC Nifty Top 20 Equal Weight Index Fund-Reg(G)" },
  { schemeCode: 153026, schemeName: "Motilal Oswal Nifty MidSmall Financial Services Index Fund-Regular Plan-Growth", fundName: "Motilal Oswal Nifty MidSmall Financial Services Index Fund-Reg(G)" },
  { schemeCode: 153323, schemeName: "SBI Nifty IT Index Fund - Regular Plan - Growth", fundName: "SBI Nifty IT Index Fund-Reg(G)" },
  { schemeCode: 153566, schemeName: "Nippon India BSE Sensex Next 30 Index Fund - Regular Plan-Growth Option", fundName: "Nippon India BSE Sensex Next 30 Index Fund-Reg(G)" },
  { schemeCode: 152574, schemeName: "Tata Nifty Financial Services Index Fund - Regular Plan - Growth", fundName: "Tata Nifty Financial Services Index Fund-Reg(G)" },
  { schemeCode: 152596, schemeName: "Tata Nifty500 Multicap Infrastructure 50:30:20 Index Fund - Regular Plan - Growth", fundName: "Tata Nifty500 Multicap Infrastructure 50:30:20 Index Fund-Reg(G)" },
  { schemeCode: 153087, schemeName: "UTI Nifty Alpha Low-Volatility 30 Index Fund - Regular Plan - Growth Option", fundName: "UTI Nifty Alpha Low-Volatility 30 Index Fund-Reg(G)" },
  { schemeCode: 153830, schemeName: "Axis Nifty500 Quality 50 Index Fund - Regular Plan - Growth Option", fundName: "Axis Nifty500 Quality 50 Index Fund-Reg(G)" },
  { schemeCode: 153271, schemeName: "UTI Nifty India Manufacturing Index Fund - Regular Plan - Growth Option", fundName: "Navi Nifty India Manufacturing Index Fund-Reg(G)" },
  { schemeCode: 153162, schemeName: "ICICI Prudential Nifty 500 Index Fund - Growth", fundName: "ICICI Pru Nifty 500 Index Fund-Reg(G)" },
  { schemeCode: 153742, schemeName: "Aditya Birla Sun Life BSE 500 Quality 50 Index Fund - Regular Growth", fundName: "Aditya Birla SL BSE 500 Quality 50 Index Fund-Reg(G)" },
  { schemeCode: 154198, schemeName: "UTI Nifty500 Shariah Index Fund - Regular Plan Growth Option", fundName: "UTI Nifty500 Shariah Index Fund-Reg(G)" },
  { schemeCode: 152765, schemeName: "KOTAK NIFTY MIDCAP 50 INDEX FUND-REGULAR PLAN-GROWTH", fundName: "Kotak NIFTY Midcap 50 Index Fund-Reg(G)" },
  { schemeCode: 153735, schemeName: "Aditya Birla Sun Life BSE 500 Momentum 50 Index Fund- Regular Growth", fundName: "Aditya Birla SL BSE 500 Momentum 50 Index Fund-Reg(G)" },
  { schemeCode: 153716, schemeName: "SBI Nifty100 Low Volatility 30 Index Fund- Regular Plan- Growth", fundName: "SBI Nifty100 Low Volatility 30 Index Fund-Reg(G)" },
  { schemeCode: 152331, schemeName: "Baroda BNP Paribas Nifty 50 Index Fund - Regular Plan - Growth option", fundName: "Baroda BNP Paribas Nifty 50 Index Fund-Reg(G)" },
  { schemeCode: 153088, schemeName: "UTI Nifty Midcap 150 Index Fund - Regular Plan - Growth Option", fundName: "UTI Nifty Midcap 150 Index Fund-Reg(G)" },
  { schemeCode: 152265, schemeName: "BANDHAN Nifty Smallcap 250 Index Fund - Regular Plan - IDCW", fundName: "Bandhan Nifty Smallcap 250 Index Fund-Reg(G)" },
  { schemeCode: 153346, schemeName: "DSP Nifty Private Bank Index Fund - Regular - IDCW", fundName: "DSP Nifty Private Bank Index Fund-Reg(G)" },
  { schemeCode: 152653, schemeName: "DSP Nifty Bank Index Fund - Regular - Growth", fundName: "DSP Nifty Bank Index Fund-Reg(G)" },
  { schemeCode: 150522, schemeName: "Motilal Oswal BSE Quality Index Fund-Regular plan", fundName: "Motilal Oswal BSE Quality Index Fund-Reg(G)" },
  { schemeCode: 153589, schemeName: "DSP Nifty IT Index Fund - Regular - IDCW", fundName: "DSP Nifty IT Index Fund-Reg(G)" },
  { schemeCode: 153597, schemeName: "Motilal Oswal BSE 1000 Index Fund - Regular Plan - Growth", fundName: "Motilal Oswal BSE 1000 Index Fund-Reg(G)" },
  { schemeCode: 153330, schemeName: "ANGEL ONE NIFTY TOTAL MARKET INDEX FUND DIRECT PLAN GROWTH OPTION", fundName: "Angel One Nifty Total Market Index Fund-Reg(G)" },
  { schemeCode: 152975, schemeName: "Mirae Asset Nifty 50 Index Fund - Regular Plan - IDCW", fundName: "Mirae Asset Nifty 50 Index Fund-Reg(G)" },
  { schemeCode: 153420, schemeName: "Tata BSE Quality Index Fund Direct plan Growth Option", fundName: "Tata BSE Quality Index Fund-Reg(G)" },
  { schemeCode: 153148, schemeName: "Kotak Nifty 50 Equal Weight Index Fund - Regular Plan - Growth", fundName: "Kotak Nifty 50 Equal Weight Index Fund-Reg(G)" },
  { schemeCode: 152423, schemeName: "Axis BSE Sensex Index Fund - Regular Plan - IDCW", fundName: "Axis BSE Sensex Index Fund-Reg(G)" },
  { schemeCode: 154064, schemeName: "Tata BSE Multicap Consumption 50:30:20 Index Fund - Regular Plan Growth Option", fundName: "Tata BSE Multicap Consumption 50:30:20 Index Fund-Reg(G)" },
  { schemeCode: 152971, schemeName: "Mirae Asset Nifty Total Market Index Fund - Regular Plan - IDCW", fundName: "Mirae Asset Nifty Total Market Index Fund-Reg(G)" },
  { schemeCode: 153232, schemeName: "Groww Nifty India Railways PSU Index Fund - Regular Plan - Growth", fundName: "Groww Nifty India Railways PSU Index Fund-Reg(G)" },
  { schemeCode: 152573, schemeName: "Tata Nifty Realty Index Fund - Regular Plan - Growth", fundName: "Tata Nifty Realty Index Fund-Reg(G)" },
  { schemeCode: 153472, schemeName: "Nippon India Nifty 500 Quality 50 Index Fund - Regular Plan - Growth Option", fundName: "Nippon India Nifty 500 Quality 50 Index Fund-Reg(G)" },
  { schemeCode: 153507, schemeName: "Bajaj Finserv Nifty 50 Index Fund - Regular - IDCW", fundName: "Bajaj Finserv Nifty 50 Index Fund-Reg(G)" },
  { schemeCode: 153222, schemeName: "Kotak Nifty SmallCap 250 Index Fund- Regular - IDCW", fundName: "Kotak Nifty Smallcap 250 Index Fund-Reg(G)" },
  { schemeCode: 152633, schemeName: "Groww Nifty Non-Cyclical Consumer Index Fund - Regular Plan - Growth", fundName: "Groww Nifty Non-Cyclical Consumer Index Fund-Reg(G)" },
  { schemeCode: 152717, schemeName: "Bandhan Nifty Total Market Index Fund - Regular Plan - Growth", fundName: "Bandhan Nifty Total Market Index Fund-Reg(G)" },
  { schemeCode: 153809, schemeName: "Nippon India Nifty India Manufacturing Index-Regular Plan-Growth Option", fundName: "Nippon India Nifty India Manufacturing Index Fund-Reg(G)" },
  { schemeCode: 153145, schemeName: "Kotak Nifty 100 Equal Weight Index Fund - Regular Plan - Growth", fundName: "Kotak Nifty 100 Equal Weight Index Fund-Reg(G)" },
  { schemeCode: 154170, schemeName: "Axis BSE India Sectors Leaders Index Fund- Regular Plan- Growth Option", fundName: "Axis BSE India Sector Leaders Index Fund-Reg(G)" },
  { schemeCode: 153061, schemeName: "Nippon India Nifty Realty Index Fund-Regular Plan- Growth Option", fundName: "Nippon India Nifty Realty Index Fund-Reg(G)" },
  { schemeCode: 152979, schemeName: "Mirae Asset Nifty LargeMidcap 250 Index Fund - Regular Plan - IDCW", fundName: "Mirae Asset Nifty LargeMidcap 250 Index Fund-Reg(G)" },
  { schemeCode: 153463, schemeName: "Kotak Nifty Top 10 Equal Weight Index Fund-Regular Plan-Growth", fundName: "Kotak Nifty Top 10 Equal Weight Index Fund-Reg(G)" },
  { schemeCode: 153028, schemeName: "Motilal Oswal Nifty MidSmall IT and Telecom Index Fund-Regular Plan-Growth", fundName: "Motilal Oswal Nifty MidSmall IT and Telecom Index Fund-Reg(G)" },
  { schemeCode: 153955, schemeName: "ANGEL ONE NIFTY TOTAL MARKET MOMENTUM QUALITY 50 INDEX FUND - REGULAR GROWTH", fundName: "Angel One Nifty Total Market Momentum Quality 50 Index Fund-Reg(G)" },
  { schemeCode: 152870, schemeName: "Kotak Nifty India Tourism Index Fund-Direct-Growth Option", fundName: "Kotak Nifty India Tourism Index Fund-Reg(G)" },
  { schemeCode: 152856, schemeName: "Bandhan Nifty Midcap 150 Index Fund-Regular Plan-Growth", fundName: "Bandhan Nifty Midcap 150 Index Fund-Reg(G)" },
  { schemeCode: 150443, schemeName: "Motilal Oswal BSE Financials ex Bank 30 Index Fund Direct Growth", fundName: "Motilal Oswal BSE Financials ex Bank 30 Index Fund-Reg(G)" },
  { schemeCode: 153529, schemeName: "ANGEL ONE NIFTY 50 INDEX FUND-DIRECT-GROWTH", fundName: "Angel One Nifty 50 Index Fund-Reg(G)" },
  { schemeCode: 153826, schemeName: "ANGEL ONE GOLD ETF", fundName: "Angel One Gold ETF FOF-Reg(G)" },
  { schemeCode: 150592, schemeName: "BANDHAN NIFTY200 MOMENTUM 30 INDEX FUND - GROWTH - REGULAR PLAN", fundName: "Bandhan Nifty 500 Momentum 50 Index Fund-Reg(G)" },
  { schemeCode: 153613, schemeName: "ICICI Prudential Nifty Top 15 Equal Weight Index Fund - Growth", fundName: "ICICI Pru Nifty Top 15 Equal Weight Index Fund-Reg(G)" },
  { schemeCode: 151738, schemeName: "UTI Nifty 500 Value 50 Index Fund - Regular Plan - Growth Option", fundName: "Bandhan Nifty 500 Value 50 Index Fund-Reg(G)" },
  { schemeCode: 153022, schemeName: "Motilal Oswal Nifty MidSmall Healthcare Index Fund-Regular Plan-Growth", fundName: "Motilal Oswal Nifty MidSmall Healthcare Index Fund-Reg(G)" },
  { schemeCode: 153475, schemeName: "Nippon India Nifty 500 Low Volatility 50 Index Fund - Regular Plan - Growth Option", fundName: "Nippon India Nifty 500 Low Volatility 50 Index Fund-Reg(G)" },
  { schemeCode: 153839, schemeName: "Bandhan BSE India Sector Leaders Index Fund - Regular Plan - Growth", fundName: "Bandhan BSE India Sector Leaders Index Fund-Reg(G)" },
  { schemeCode: 152044, schemeName: "Bandhan Nifty IT Index Fund - Regular Plan - IDCW", fundName: "Bandhan Nifty IT Index Fund-Reg(G)" },
  { schemeCode: 153349, schemeName: "Bandhan Nifty Next 50 Index Fund - Regular Plan - Growth", fundName: "Bandhan Nifty Next 50 Index Fund-Reg(G)" },
  { schemeCode: 152750, schemeName: "Navi Nifty 500 Multicap 50:25:25 Index Fund-Reg(G)", fundName: "Navi Nifty 500 Multicap 50:25:25 Index Fund-Reg(G)" },
  { schemeCode: 153363, schemeName: "Navi Nifty Smallcap250 Momentum Quality 100 Index Fund-Reg(G)", fundName: "Navi Nifty Smallcap250 Momentum Quality 100 Index Fund-Reg(G)" },
  { schemeCode: 153784, schemeName: "Kotak Nifty Alpha 50 Index Fund - Regular Plan - Growth", fundName: "Kotak Nifty Alpha 50 Index Fund-Reg(G)" },
  { schemeCode: 151763, schemeName: "UTI BSE Housing Index Fund - Regular Plan - Growth Option", fundName: "UTI BSE Housing Index Fund-Reg(G)" },
  { schemeCode: 152930, schemeName: "Baroda BNP Paribas Nifty200 Momentum 30 Index Fund - Regular Plan - Growth Option", fundName: "Baroda BNP Paribas Nifty200 Momentum 30 Index Fund-Reg(G)" },
  { schemeCode: 153544, schemeName: "ICICI Prudential Nifty200 Quality 30 Index Fund - Growth", fundName: "ICICI Pru Nifty200 Quality 30 Index Fund-Reg(G)" },
  { schemeCode: 153024, schemeName: "Motilal Oswal Nifty MidSmall India Consumption Index Fund-Regular Plan-Growth", fundName: "Motilal Oswal Nifty MidSmall India Consumption Index Fund-Reg(G)" },
  { schemeCode: 153580, schemeName: "Tata Nifty Midcap 150 Index Fund - Regular Plan - Growth Option", fundName: "Kotak Nifty Midcap 150 Index Fund-Reg(G)" },
  { schemeCode: 149802, schemeName: "UTI BSE Sensex Index Fund - Regular Plan  -Growth Option", fundName: "Navi BSE Sensex Index Fund-Reg(G)" },
  { schemeCode: 146379, schemeName: "DSP Nifty 50 Index Fund - Regular Plan - Growth", fundName: "Groww Nifty 50 Index Fund-Reg(G)" },
  { schemeCode: 152792, schemeName: "Bandhan Nifty Bank Index Fund - Regular Plan - Growth", fundName: "Bandhan Nifty Bank Index Fund-Reg(G)" },
  { schemeCode: 152865, schemeName: "UTI Nifty Private Bank Index Fund - Regular Plan - Growth Option", fundName: "ICICI Pru Nifty Private Bank Index Fund-Reg(G)" },
  { schemeCode: 154030, schemeName: "Kotak Nifty500 Momentum 50 Index Fund - Regular Plan - Growth", fundName: "Kotak Nifty500 Momentum 50 Index Fund-Reg(G)" },
  { schemeCode: 152843, schemeName: "Bandhan BSE Healthcare Index Fund Regular Plan - Growth", fundName: "Bandhan BSE Healthcare Index Fund-Reg(G)" },
  { schemeCode: 153285, schemeName: "Kotak BSE Sensex Index Fund - Regular - IDCW", fundName: "Kotak BSE Sensex Index Fund-Reg(G)" },
  { schemeCode: 153217, schemeName: "DSP BSE SENSEX Next 30 Index Fund - Regular - IDCW", fundName: "DSP BSE Sensex Next 30 Index Fund-Reg(G)" },
  { schemeCode: 153659, schemeName: "KOTAK NIFTY 200 QUALITY 30 INDEX FUND - REGULAR PLAN - GROWTH", fundName: "Kotak Nifty 200 Quality 30 Index Fund-Reg(G)" },
  { schemeCode: 152038, schemeName: "Kotak  BSE Housing Index Fund - Regular Plan - Growth Option", fundName: "Kotak BSE Housing Index Fund-Reg(G)" },
  { schemeCode: 154092, schemeName: "The Wealth Company Gold ETF", fundName: "The Wealth Company Gold ETF FOF-Reg(G)" },
  { schemeCode: 154012, schemeName: "DSP Nifty Midcap 150 Index Fund - Regular - Growth", fundName: "Groww Nifty Midcap 150 Index Fund-Reg(G)" },
  { schemeCode: 153113, schemeName: "Bandhan Nifty 200 Quality 30 Index Fund - Regular Plan - Growth", fundName: "Bandhan Nifty 200 Quality 30 Index Fund-Reg(G)" },
  { schemeCode: 153212, schemeName: "Bandhan Nifty Alpha Low Volatility 30 Index Fund - Regular Plan - Growth", fundName: "Bandhan Nifty Alpha Low Volatility 30 Index Fund-Reg(G)" },
  { schemeCode: 154091, schemeName: "DSP Nifty 500 Index Fund - Regular - IDCW", fundName: "DSP Nifty 500 Index Fund-Reg(G)" },
  { schemeCode: 154147, schemeName: "Kotak Nifty200 Value 30 Index Fund - Regular - IDCW", fundName: "Kotak Nifty200 Value 30 Index Fund-Reg(G)" },
  { schemeCode: 154027, schemeName: "Navi Nifty midsmallcap 400 Index Fund- Direct - Growth", fundName: "Navi Nifty MidSmallcap 400 Index Fund-Reg(G)" },
  { schemeCode: 154013, schemeName: "DSP Nifty Midcap 150 Index Fund - Regular - IDCW", fundName: "DSP Nifty Midcap 150 Index Fund-Reg(G)" },
  { schemeCode: 154017, schemeName: "DSP Nifty Smallcap 250 Index Fund - Regular - IDCW", fundName: "DSP Nifty Smallcap 250 Index Fund-Reg(G)" },
  { schemeCode: 153001, schemeName: "Baroda BNP Paribas Nifty Midcap 150 Index Fund - Regular Plan - Growth Option", fundName: "Baroda BNP Paribas NIFTY Midcap 150 Index Fund-Reg(G)" },
  { schemeCode: 148365, schemeName: "L&T Nifty Next 50 Index Fund - Regular Plan - Growth Option", fundName: "Groww Nifty Next 50 Index Fund-Reg(G)" },
  { schemeCode: 112948, schemeName: "Taurus Nifty 50 Index Fund - Regular Plan - Growth", fundName: "Taurus Nifty 50 Index Fund-Reg(G)" },
  { schemeCode: 152653, schemeName: "DSP Nifty Bank Index Fund - Regular - Growth", fundName: "Groww Nifty PSU Bank Index Fund-Reg(G)" },
]

/** Returns the pre-computed scheme entries instantly. */
export async function discoverSchemeEntries(): Promise<SchemeEntry[]> {
  return SCHEME_ENTRIES
}
