-- FactorLens Schema Migration
-- Run this in your new Supabase SQL Editor:
-- https://supabase.com/dashboard/project/lerpchldswooqrfscuig/editor

-- ── 1. funds ──────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS funds (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code             TEXT        NOT NULL UNIQUE,
    name             TEXT        NOT NULL,
    category         TEXT,
    inception_date   TEXT,
    cagr             NUMERIC,
    avg_3y_rolling_return NUMERIC,
    max_drawdown     NUMERIC,
    volatility       NUMERIC,
    sharpe_ratio     NUMERIC,
    calmar_ratio     NUMERIC,
    cagr_1y          NUMERIC,
    cagr_3y          NUMERIC,
    cagr_5y          NUMERIC,
    cagr_10y         NUMERIC,
    cagr_20y         NUMERIC,
    score            NUMERIC,
    final_rank       INTEGER
);

-- Migration: add period CAGR columns if upgrading an existing DB
ALTER TABLE funds ADD COLUMN IF NOT EXISTS cagr_1y  NUMERIC;
ALTER TABLE funds ADD COLUMN IF NOT EXISTS cagr_3y  NUMERIC;
ALTER TABLE funds ADD COLUMN IF NOT EXISTS cagr_5y  NUMERIC;
ALTER TABLE funds ADD COLUMN IF NOT EXISTS cagr_10y NUMERIC;
ALTER TABLE funds ADD COLUMN IF NOT EXISTS cagr_20y NUMERIC;

-- ── 2. nav_data ───────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS nav_data (
    fund_id          BIGINT  NOT NULL REFERENCES funds(id) ON DELETE CASCADE,
    date             DATE    NOT NULL,
    nav_value        NUMERIC NOT NULL,
    PRIMARY KEY (fund_id, date)
);

CREATE INDEX IF NOT EXISTS idx_nav_data_fund_date ON nav_data (fund_id, date);

-- ── 3. mf_funds ───────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS mf_funds (
    scheme_code      INTEGER     PRIMARY KEY,
    scheme_name      TEXT        NOT NULL,
    fund_house       TEXT,
    scheme_type      TEXT,
    scheme_category  TEXT,
    search_name      TEXT,
    match_ratio      NUMERIC(5,3),
    created_at       TIMESTAMPTZ DEFAULT NOW()
);

-- ── 4. mf_nav_data ────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS mf_nav_data (
    scheme_code      INTEGER NOT NULL REFERENCES mf_funds(scheme_code) ON DELETE CASCADE,
    date             DATE    NOT NULL,
    nav              NUMERIC(20,4) NOT NULL,
    PRIMARY KEY (scheme_code, date)
);

CREATE INDEX IF NOT EXISTS idx_mf_nav_scheme_date ON mf_nav_data (scheme_code, date);

-- ── 5. mf_funds computed columns ──────────────────────────────────────────────
-- Migration: add pre-computed NAV + return columns so the API can serve
-- the funds page instantly without hitting mfapi.in on every page load.
ALTER TABLE mf_funds ADD COLUMN IF NOT EXISTS nav        NUMERIC(20,4);
ALTER TABLE mf_funds ADD COLUMN IF NOT EXISTS nav_date   DATE;
ALTER TABLE mf_funds ADD COLUMN IF NOT EXISTS return_1y  NUMERIC(8,4);
ALTER TABLE mf_funds ADD COLUMN IF NOT EXISTS return_3y  NUMERIC(8,4);
ALTER TABLE mf_funds ADD COLUMN IF NOT EXISTS return_5y  NUMERIC(8,4);
ALTER TABLE mf_funds ADD COLUMN IF NOT EXISTS last_sync  TIMESTAMPTZ;
